controller:
  replicaCount: 1
  nodeSelector:
    kubernetes.io/os: linux
  service:
    externalTrafficPolicy: Local
  progressDeadlineSeconds: 600
  admissionWebhooks:
    patch:
      nodeSelector:
        kubernetes.io/os: linux

defaultBackend:
  nodeSelector:
    kubernetes.io/os: linux
